
package com.microsoft.schemas.exchange.services._2006.messages;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ExchangeServicePortType", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.microsoft.schemas.exchange.services._2006.messages.ObjectFactory.class,
    com.microsoft.schemas.exchange.services._2006.types.ObjectFactory.class
})
public interface ExchangeServicePortType {


    /**
     * 
     * @param resolveNamesResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "ResolveNames", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ResolveNames")
    public void resolveNames(
        @WebParam(name = "ResolveNames", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        ResolveNamesType request,
        @WebParam(name = "ResolveNamesResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "ResolveNamesResult")
        Holder<ResolveNamesResponseType> resolveNamesResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param expandDLResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "ExpandDL", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ExpandDL")
    public void expandDL(
        @WebParam(name = "ExpandDL", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        ExpandDLType request,
        @WebParam(name = "ExpandDLResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "ExpandDLResult")
        Holder<ExpandDLResponseType> expandDLResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getServerTimeZonesResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "GetServerTimeZones", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetServerTimeZones")
    public void getServerTimeZones(
        @WebParam(name = "GetServerTimeZones", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetServerTimeZonesType request,
        @WebParam(name = "GetServerTimeZonesResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetServerTimeZonesResult")
        Holder<GetServerTimeZonesResponseType> getServerTimeZonesResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param findFolderResult
     */
    @WebMethod(operationName = "FindFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/FindFolder")
    public void findFolder(
        @WebParam(name = "FindFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        FindFolderType request,
        @WebParam(name = "FindFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "FindFolderResult")
        Holder<FindFolderResponseType> findFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param findItemResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "FindItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/FindItem")
    public void findItem(
        @WebParam(name = "FindItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        FindItemType request,
        @WebParam(name = "FindItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "FindItemResult")
        Holder<FindItemResponseType> findItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getFolderResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "GetFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetFolder")
    public void getFolder(
        @WebParam(name = "GetFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetFolderType request,
        @WebParam(name = "GetFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetFolderResult")
        Holder<GetFolderResponseType> getFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param convertIdResult
     */
    @WebMethod(operationName = "ConvertId", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ConvertId")
    public void convertId(
        @WebParam(name = "ConvertId", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        ConvertIdType request,
        @WebParam(name = "ConvertIdResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "ConvertIdResult")
        Holder<ConvertIdResponseType> convertIdResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param uploadItemsResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "UploadItems", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UploadItems")
    public void uploadItems(
        @WebParam(name = "UploadItems", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UploadItemsType request,
        @WebParam(name = "UploadItemsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UploadItemsResult")
        Holder<UploadItemsResponseType> uploadItemsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param exportItemsResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "ExportItems", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ExportItems")
    public void exportItems(
        @WebParam(name = "ExportItems", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        ExportItemsType request,
        @WebParam(name = "ExportItemsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "ExportItemsResult")
        Holder<ExportItemsResponseType> exportItemsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param createFolderResult
     */
    @WebMethod(operationName = "CreateFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateFolder")
    public void createFolder(
        @WebParam(name = "CreateFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CreateFolderType request,
        @WebParam(name = "CreateFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CreateFolderResult")
        Holder<CreateFolderResponseType> createFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param deleteFolderResult
     */
    @WebMethod(operationName = "DeleteFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteFolder")
    public void deleteFolder(
        @WebParam(name = "DeleteFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        DeleteFolderType request,
        @WebParam(name = "DeleteFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "DeleteFolderResult")
        Holder<DeleteFolderResponseType> deleteFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param emptyFolderResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "EmptyFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/EmptyFolder")
    public void emptyFolder(
        @WebParam(name = "EmptyFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        EmptyFolderType request,
        @WebParam(name = "EmptyFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "EmptyFolderResult")
        Holder<EmptyFolderResponseType> emptyFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param updateFolderResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "UpdateFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateFolder")
    public void updateFolder(
        @WebParam(name = "UpdateFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UpdateFolderType request,
        @WebParam(name = "UpdateFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UpdateFolderResult")
        Holder<UpdateFolderResponseType> updateFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param moveFolderResult
     */
    @WebMethod(operationName = "MoveFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/MoveFolder")
    public void moveFolder(
        @WebParam(name = "MoveFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        MoveFolderType request,
        @WebParam(name = "MoveFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "MoveFolderResult")
        Holder<MoveFolderResponseType> moveFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param copyFolderResult
     */
    @WebMethod(operationName = "CopyFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CopyFolder")
    public void copyFolder(
        @WebParam(name = "CopyFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CopyFolderType request,
        @WebParam(name = "CopyFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CopyFolderResult")
        Holder<CopyFolderResponseType> copyFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param subscribeResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "Subscribe", action = "http://schemas.microsoft.com/exchange/services/2006/messages/Subscribe")
    public void subscribe(
        @WebParam(name = "Subscribe", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        SubscribeType request,
        @WebParam(name = "SubscribeResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "SubscribeResult")
        Holder<SubscribeResponseType> subscribeResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param unsubscribeResult
     */
    @WebMethod(operationName = "Unsubscribe", action = "http://schemas.microsoft.com/exchange/services/2006/messages/Unsubscribe")
    public void unsubscribe(
        @WebParam(name = "Unsubscribe", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UnsubscribeType request,
        @WebParam(name = "UnsubscribeResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UnsubscribeResult")
        Holder<UnsubscribeResponseType> unsubscribeResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param getEventsResult
     */
    @WebMethod(operationName = "GetEvents", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetEvents")
    public void getEvents(
        @WebParam(name = "GetEvents", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetEventsType request,
        @WebParam(name = "GetEventsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetEventsResult")
        Holder<GetEventsResponseType> getEventsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param getStreamingEventsResult
     */
    @WebMethod(operationName = "GetStreamingEvents", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetEvents")
    public void getStreamingEvents(
        @WebParam(name = "GetStreamingEvents", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetStreamingEventsType request,
        @WebParam(name = "GetStreamingEventsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetStreamingEventsResult")
        Holder<GetStreamingEventsResponseType> getStreamingEventsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param syncFolderHierarchyResult
     */
    @WebMethod(operationName = "SyncFolderHierarchy", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SyncFolderHierarchy")
    public void syncFolderHierarchy(
        @WebParam(name = "SyncFolderHierarchy", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        SyncFolderHierarchyType request,
        @WebParam(name = "SyncFolderHierarchyResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "SyncFolderHierarchyResult")
        Holder<SyncFolderHierarchyResponseType> syncFolderHierarchyResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param syncFolderItemsResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "SyncFolderItems", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SyncFolderItems")
    public void syncFolderItems(
        @WebParam(name = "SyncFolderItems", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        SyncFolderItemsType request,
        @WebParam(name = "SyncFolderItemsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "SyncFolderItemsResult")
        Holder<SyncFolderItemsResponseType> syncFolderItemsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getItemResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "GetItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetItem")
    public void getItem(
        @WebParam(name = "GetItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetItemType request,
        @WebParam(name = "GetItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetItemResult")
        Holder<GetItemResponseType> getItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param createItemResult
     */
    @WebMethod(operationName = "CreateItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateItem")
    public void createItem(
        @WebParam(name = "CreateItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CreateItemType request,
        @WebParam(name = "CreateItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CreateItemResult")
        Holder<CreateItemResponseType> createItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param deleteItemResult
     */
    @WebMethod(operationName = "DeleteItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteItem")
    public void deleteItem(
        @WebParam(name = "DeleteItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        DeleteItemType request,
        @WebParam(name = "DeleteItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "DeleteItemResult")
        Holder<DeleteItemResponseType> deleteItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param updateItemResult
     */
    @WebMethod(operationName = "UpdateItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateItem")
    public void updateItem(
        @WebParam(name = "UpdateItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UpdateItemType request,
        @WebParam(name = "UpdateItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UpdateItemResult")
        Holder<UpdateItemResponseType> updateItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param sendItemResult
     */
    @WebMethod(operationName = "SendItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SendItem")
    public void sendItem(
        @WebParam(name = "SendItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        SendItemType request,
        @WebParam(name = "SendItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "SendItemResult")
        Holder<SendItemResponseType> sendItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param moveItemResult
     */
    @WebMethod(operationName = "MoveItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/MoveItem")
    public void moveItem(
        @WebParam(name = "MoveItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        MoveItemType request,
        @WebParam(name = "MoveItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "MoveItemResult")
        Holder<MoveItemResponseType> moveItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param copyItemResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "CopyItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CopyItem")
    public void copyItem(
        @WebParam(name = "CopyItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CopyItemType request,
        @WebParam(name = "CopyItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CopyItemResult")
        Holder<CopyItemResponseType> copyItemResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param createAttachmentResult
     */
    @WebMethod(operationName = "CreateAttachment", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateAttachment")
    public void createAttachment(
        @WebParam(name = "CreateAttachment", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CreateAttachmentType request,
        @WebParam(name = "CreateAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CreateAttachmentResult")
        Holder<CreateAttachmentResponseType> createAttachmentResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param deleteAttachmentResult
     */
    @WebMethod(operationName = "DeleteAttachment", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteAttachment")
    public void deleteAttachment(
        @WebParam(name = "DeleteAttachment", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        DeleteAttachmentType request,
        @WebParam(name = "DeleteAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "DeleteAttachmentResult")
        Holder<DeleteAttachmentResponseType> deleteAttachmentResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getAttachmentResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "GetAttachment", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetAttachment")
    public void getAttachment(
        @WebParam(name = "GetAttachment", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetAttachmentType request,
        @WebParam(name = "GetAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetAttachmentResult")
        Holder<GetAttachmentResponseType> getAttachmentResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param createManagedFolderResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "CreateManagedFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateManagedFolder")
    public void createManagedFolder(
        @WebParam(name = "CreateManagedFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CreateManagedFolderRequestType request,
        @WebParam(name = "CreateManagedFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CreateManagedFolderResult")
        Holder<CreateManagedFolderResponseType> createManagedFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getDelegateResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "GetDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetDelegate")
    public void getDelegate(
        @WebParam(name = "GetDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetDelegateType request,
        @WebParam(name = "GetDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetDelegateResult")
        Holder<GetDelegateResponseMessageType> getDelegateResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param addDelegateResult
     */
    @WebMethod(operationName = "AddDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/AddDelegate")
    public void addDelegate(
        @WebParam(name = "AddDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        AddDelegateType request,
        @WebParam(name = "AddDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "AddDelegateResult")
        Holder<AddDelegateResponseMessageType> addDelegateResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param removeDelegateResult
     */
    @WebMethod(operationName = "RemoveDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/RemoveDelegate")
    public void removeDelegate(
        @WebParam(name = "RemoveDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        RemoveDelegateType request,
        @WebParam(name = "RemoveDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "RemoveDelegateResult")
        Holder<RemoveDelegateResponseMessageType> removeDelegateResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param updateDelegateResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "UpdateDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateDelegate")
    public void updateDelegate(
        @WebParam(name = "UpdateDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UpdateDelegateType request,
        @WebParam(name = "UpdateDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UpdateDelegateResult")
        Holder<UpdateDelegateResponseMessageType> updateDelegateResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param createUserConfigurationResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "CreateUserConfiguration", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateUserConfiguration")
    public void createUserConfiguration(
        @WebParam(name = "CreateUserConfiguration", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        CreateUserConfigurationType request,
        @WebParam(name = "CreateUserConfigurationResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "CreateUserConfigurationResult")
        Holder<CreateUserConfigurationResponseType> createUserConfigurationResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param deleteUserConfigurationResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "DeleteUserConfiguration", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteUserConfiguration")
    public void deleteUserConfiguration(
        @WebParam(name = "DeleteUserConfiguration", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        DeleteUserConfigurationType request,
        @WebParam(name = "DeleteUserConfigurationResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "DeleteUserConfigurationResult")
        Holder<DeleteUserConfigurationResponseType> deleteUserConfigurationResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param getUserConfigurationResult
     */
    @WebMethod(operationName = "GetUserConfiguration", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetUserConfiguration")
    public void getUserConfiguration(
        @WebParam(name = "GetUserConfiguration", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetUserConfigurationType request,
        @WebParam(name = "GetUserConfigurationResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetUserConfigurationResult")
        Holder<GetUserConfigurationResponseType> getUserConfigurationResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param updateUserConfigurationResult
     */
    @WebMethod(operationName = "UpdateUserConfiguration", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateUserConfiguration")
    public void updateUserConfiguration(
        @WebParam(name = "UpdateUserConfiguration", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UpdateUserConfigurationType request,
        @WebParam(name = "UpdateUserConfigurationResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UpdateUserConfigurationResult")
        Holder<UpdateUserConfigurationResponseType> updateUserConfigurationResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getUserAvailabilityRequest
     * @param serverVersion
     * @param getUserAvailabilityResult
     */
    @WebMethod(operationName = "GetUserAvailability", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetUserAvailability")
    public void getUserAvailability(
        @WebParam(name = "GetUserAvailabilityRequest", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "GetUserAvailabilityRequest")
        GetUserAvailabilityRequestType getUserAvailabilityRequest,
        @WebParam(name = "GetUserAvailabilityResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetUserAvailabilityResult")
        Holder<GetUserAvailabilityResponseType> getUserAvailabilityResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getUserOofSettingsResult
     * @param serverVersion
     * @param getUserOofSettingsRequest
     */
    @WebMethod(operationName = "GetUserOofSettings", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetUserOofSettings")
    public void getUserOofSettings(
        @WebParam(name = "GetUserOofSettingsRequest", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "GetUserOofSettingsRequest")
        GetUserOofSettingsRequest getUserOofSettingsRequest,
        @WebParam(name = "GetUserOofSettingsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetUserOofSettingsResult")
        Holder<GetUserOofSettingsResponse> getUserOofSettingsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param setUserOofSettingsRequest
     * @param serverVersion
     * @param setUserOofSettingsResult
     */
    @WebMethod(operationName = "SetUserOofSettings", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SetUserOofSettings")
    public void setUserOofSettings(
        @WebParam(name = "SetUserOofSettingsRequest", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "SetUserOofSettingsRequest")
        SetUserOofSettingsRequest setUserOofSettingsRequest,
        @WebParam(name = "SetUserOofSettingsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "SetUserOofSettingsResult")
        Holder<SetUserOofSettingsResponse> setUserOofSettingsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param getServiceConfigurationResult
     */
    @WebMethod(operationName = "GetServiceConfiguration", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetServiceConfiguration")
    public void getServiceConfiguration(
        @WebParam(name = "GetServiceConfiguration", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetServiceConfigurationType request,
        @WebParam(name = "GetServiceConfigurationResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetServiceConfigurationResult")
        Holder<GetServiceConfigurationResponseMessageType> getServiceConfigurationResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getMailTipsResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "GetMailTips", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetMailTips")
    public void getMailTips(
        @WebParam(name = "GetMailTips", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetMailTipsType request,
        @WebParam(name = "GetMailTipsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetMailTipsResult")
        Holder<GetMailTipsResponseMessageType> getMailTipsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param playOnPhoneResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "PlayOnPhone", action = "http://schemas.microsoft.com/exchange/services/2006/messages/PlayOnPhone")
    public void playOnPhone(
        @WebParam(name = "PlayOnPhone", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        PlayOnPhoneType request,
        @WebParam(name = "PlayOnPhoneResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "PlayOnPhoneResult")
        Holder<PlayOnPhoneResponseMessageType> playOnPhoneResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param getPhoneCallInformationResult
     */
    @WebMethod(operationName = "GetPhoneCallInformation", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetPhoneCallInformation")
    public void getPhoneCallInformation(
        @WebParam(name = "GetPhoneCallInformation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetPhoneCallInformationType request,
        @WebParam(name = "GetPhoneCallInformationResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetPhoneCallInformationResult")
        Holder<GetPhoneCallInformationResponseMessageType> getPhoneCallInformationResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param disconnectPhoneCallResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "DisconnectPhoneCall", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DisconnectPhoneCall")
    public void disconnectPhoneCall(
        @WebParam(name = "DisconnectPhoneCall", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        DisconnectPhoneCallType request,
        @WebParam(name = "DisconnectPhoneCallResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "DisconnectPhoneCallResult")
        Holder<DisconnectPhoneCallResponseMessageType> disconnectPhoneCallResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param getSharingMetadataResult
     */
    @WebMethod(operationName = "GetSharingMetadata", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetSharingMetadata")
    public void getSharingMetadata(
        @WebParam(name = "GetSharingMetadata", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetSharingMetadataType request,
        @WebParam(name = "GetSharingMetadataResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetSharingMetadataResult")
        Holder<GetSharingMetadataResponseMessageType> getSharingMetadataResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param refreshSharingFolderResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "RefreshSharingFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/RefreshSharingFolder")
    public void refreshSharingFolder(
        @WebParam(name = "RefreshSharingFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        RefreshSharingFolderType request,
        @WebParam(name = "RefreshSharingFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "RefreshSharingFolderResult")
        Holder<RefreshSharingFolderResponseMessageType> refreshSharingFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getSharingFolderResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "GetSharingFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetSharingFolder")
    public void getSharingFolder(
        @WebParam(name = "GetSharingFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetSharingFolderType request,
        @WebParam(name = "GetSharingFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetSharingFolderResult")
        Holder<GetSharingFolderResponseMessageType> getSharingFolderResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param serverVersion
     * @param getRoomListsRequest
     * @param getRoomListsResult
     */
    @WebMethod(operationName = "GetRoomLists", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetRoomLists")
    public void getRoomLists(
        @WebParam(name = "GetRoomLists", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "GetRoomListsRequest")
        GetRoomListsType getRoomListsRequest,
        @WebParam(name = "GetRoomListsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetRoomListsResult")
        Holder<GetRoomListsResponseMessageType> getRoomListsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getRoomsRequest
     * @param getRoomsResult
     * @param serverVersion
     */
    @WebMethod(operationName = "GetRooms", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetRooms")
    public void getRooms(
        @WebParam(name = "GetRooms", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "GetRoomsRequest")
        GetRoomsType getRoomsRequest,
        @WebParam(name = "GetRoomsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetRoomsResult")
        Holder<GetRoomsResponseMessageType> getRoomsResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param findMessageTrackingReportResult
     */
    @WebMethod(operationName = "FindMessageTrackingReport", action = "http://schemas.microsoft.com/exchange/services/2006/messages/FindMessageTrackingReport")
    public void findMessageTrackingReport(
        @WebParam(name = "FindMessageTrackingReport", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        FindMessageTrackingReportRequestType request,
        @WebParam(name = "FindMessageTrackingReportResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "FindMessageTrackingReportResult")
        Holder<FindMessageTrackingReportResponseMessageType> findMessageTrackingReportResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getMessageTrackingReportResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "GetMessageTrackingReport", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetMessageTrackingReport")
    public void getMessageTrackingReport(
        @WebParam(name = "GetMessageTrackingReport", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetMessageTrackingReportRequestType request,
        @WebParam(name = "GetMessageTrackingReportResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetMessageTrackingReportResult")
        Holder<GetMessageTrackingReportResponseMessageType> getMessageTrackingReportResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param request
     * @param serverVersion
     * @param findConversationResult
     */
    @WebMethod(operationName = "FindConversation", action = "http://schemas.microsoft.com/exchange/services/2006/messages/FindConversation")
    public void findConversation(
        @WebParam(name = "FindConversation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        FindConversationType request,
        @WebParam(name = "FindConversationResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "FindConversationResult")
        Holder<FindConversationResponseMessageType> findConversationResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param applyConversationActionResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "ApplyConversationAction", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ApplyConversationAction")
    public void applyConversationAction(
        @WebParam(name = "ApplyConversationAction", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        ApplyConversationActionType request,
        @WebParam(name = "ApplyConversationActionResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "ApplyConversationActionResult")
        Holder<ApplyConversationActionResponseType> applyConversationActionResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param getInboxRulesResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "GetInboxRules", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetInboxRules")
    public void getInboxRules(
        @WebParam(name = "GetInboxRules", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        GetInboxRulesRequestType request,
        @WebParam(name = "GetInboxRulesResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "GetInboxRulesResult")
        Holder<GetInboxRulesResponseType> getInboxRulesResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

    /**
     * 
     * @param updateInboxRulesResult
     * @param request
     * @param serverVersion
     */
    @WebMethod(operationName = "UpdateInboxRules", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateInboxRules")
    public void updateInboxRules(
        @WebParam(name = "UpdateInboxRules", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", partName = "request")
        UpdateInboxRulesRequestType request,
        @WebParam(name = "UpdateInboxRulesResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", mode = WebParam.Mode.OUT, partName = "UpdateInboxRulesResult")
        Holder<UpdateInboxRulesResponseType> updateInboxRulesResult,
        @WebParam(name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true, mode = WebParam.Mode.OUT, partName = "ServerVersion")
        Holder<ServerVersionInfo> serverVersion);

}
